name: Build and Publish Windows11-Debloater

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (if not using auto versioning)'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller (if not in requirements)
      run: pip install pyinstaller

    - name: Determine Version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ startsWith(github.ref, 'refs/tags/v') }}" == "true" ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        elif [[ -n "${{ github.event.inputs.version }}" ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT
        fi
        echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Update Version
      run: |
        # Update version in setup.py
        sed -i "s/version=\"[^\"]*\"/version=\"${{ steps.version.outputs.VERSION }}\"/g" setup.py
      shell: bash

    - name: Build EXE using PyInstaller
      run: |
        # Make sure app icon exists - create a blank one if it doesn't
        mkdir -p windows-debloater/src/assets/images
        if [ ! -f windows-debloater/src/assets/images/app_icon.ico ]; then
          echo "Warning: app_icon.ico not found, generating blank icon"
          pip install Pillow
          python -c "from PIL import Image; img = Image.new('RGBA', (256, 256), color=(0, 120, 212)); img.save('windows-debloater/src/assets/images/app_icon.ico')"
        fi
        
        # Make sure splash image exists - create a blank one if it doesn't
        if [ ! -f windows-debloater/src/assets/images/splash.png ]; then
          echo "Warning: splash.png not found, generating blank splash"
          pip install Pillow
          python -c "from PIL import Image, ImageDraw, ImageFont; img = Image.new('RGBA', (500, 300), color=(255, 255, 255)); draw = ImageDraw.Draw(img); draw.text((250, 150), 'Windows11-Debloater', fill=(0, 0, 0), anchor='mm'); img.save('windows-debloater/src/assets/images/splash.png')"
        fi
        
        pyinstaller --onefile --name "Windows11-Debloater-${{ steps.version.outputs.VERSION }}" --icon=windows-debloater/src/assets/images/app_icon.ico --add-data "windows-debloater/src/assets;assets/" windows-debloater/src/main.py
      shell: bash

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Windows11-Debloater-${{ steps.version.outputs.VERSION }}
        path: dist/Windows11-Debloater-${{ steps.version.outputs.VERSION }}.exe

    - name: Generate Release Notes
      id: release_notes
      run: |
        echo "# Windows11-Debloater ${{ steps.version.outputs.VERSION }} (${{ steps.version.outputs.DATE }})" > release_notes.md
        echo "" >> release_notes.md
        echo "## What's New" >> release_notes.md
        echo "- Automated build from GitHub Actions" >> release_notes.md
        echo "- Release version: ${{ steps.version.outputs.VERSION }}" >> release_notes.md
        echo "" >> release_notes.md
        echo "## Installation" >> release_notes.md
        echo "- Download the executable and run with administrator privileges" >> release_notes.md
      shell: bash
      
    - name: Create GitHub Release
      id: create_release
      if: github.event_name != 'pull_request' # Skip releases on PRs
      uses: softprops/action-gh-release@v2.2.1
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        name: Windows11-Debloater v${{ steps.version.outputs.VERSION }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        files: dist/Windows11-Debloater-${{ steps.version.outputs.VERSION }}.exe
        fail_on_unmatched_files: true
        generate_release_notes: true
        append_body: true
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
